name: ottu
description: A new flutter payment sdk
version: 0.1.6
homepage: https://github.com/sdkpayment/Flutter-SDK.git

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_localization: ^0.1.14
  intl: ^0.19.0
  http: ^1.2.0
#  webview_flutter: ^4.4.4
  webview_flutter: ^3.0.1
  web_socket_channel: ^2.4.0
  flutter_windowmanager: ^0.2.0
  flutter_jailbreak_detection:
    git:
      url: https://github.com/prodtcoorg/flutter_jailbreak_detection.git
      ref: master
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.0
  encrypt: ^5.0.3
  basic_utils: ^5.7.0
  fluttertoast: ^8.2.4
  pem: ^2.0.4
  flutter_svg: ^2.0.9
  flutter_lints: ^3.0.1


dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.ottu
        pluginClass: OttuPlugin
      ios:
        pluginClass: OttuPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/ottu/assets/visa.png
    - packages/ottu/assets/jcb.png
    - packages/ottu/assets/verve.png
    - packages/ottu/assets/discover.png
    - packages/ottu/assets/american_express.png
    - packages/ottu/assets/dinners_club.png
    - packages/ottu/assets/delete.png
    - packages/ottu/assets/apple_logo.png
    - packages/ottu/assets/card_cvv.png
    - packages/ottu/assets/card_name.png
    - packages/ottu/assets/card_number.png
    - packages/ottu/assets/card_date.png
    - packages/ottu/assets/success.png
    - packages/ottu/assets/failed.png
    - packages/ottu/assets/Mastercard_logo.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
